name: Build Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "backend/**"
  workflow_dispatch:
  
defaults:
  run:
    working-directory: backend/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -ntp package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=fdiba-ci-demo-backend

      - name: Set outputs
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short=6 HEAD)" >> $GITHUB_OUTPUT

      - name: Docker Login
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker build -t stanyorgov/ci-demo-backend:latest -t stanyorgov/ci-demo-backend:${{steps.sha_short.outputs.sha_short}} .

      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push blubito/scagile-sentinel --all-tags
        