name: Build Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "backend/**"
  workflow_dispatch:
  
defaults:
  run:
    working-directory: backend/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=StanYorgov_ci-demo
